# Generated by Django 5.1.6 on 2025-02-11 00:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("theme", models.CharField(blank=True, max_length=20, null=True)),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "reset_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("reset_token_expires", models.DateTimeField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("N", "Prefer not to say"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kilograms", max_digits=5
                    ),
                ),
                (
                    "target_weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target weight in kilograms",
                        max_digits=5,
                    ),
                ),
                ("medical_conditions", models.JSONField(blank=True, default=list)),
                ("medications", models.JSONField(blank=True, default=list)),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("dietary_restrictions", models.JSONField(blank=True, default=list)),
                (
                    "fitness_goal",
                    models.CharField(
                        choices=[
                            ("WL", "Weight Loss"),
                            ("MG", "Muscle Gain"),
                            ("MT", "Maintenance"),
                            ("GF", "General Fitness"),
                            ("AP", "Athletic Performance"),
                        ],
                        default="GF",
                        max_length=2,
                    ),
                ),
                (
                    "activity_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Sedentary"),
                            (2, "Lightly Active"),
                            (3, "Moderately Active"),
                            (4, "Very Active"),
                            (5, "Extremely Active"),
                        ],
                        default=1,
                    ),
                ),
                ("exercise_preferences", models.JSONField(default=list)),
                (
                    "daily_calorie_goal",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "macros_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="JSON containing protein, carbs, and fat goals in grams",
                    ),
                ),
                (
                    "meal_preference",
                    models.JSONField(
                        default=dict,
                        help_text="JSON containing meal timing and frequency preferences",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
